<?php
//so this file should be autogenerated by FE-builder. meh..

//for the patch-save, we're gonna need the string based parameters for sure..
//so they are key=>value.
//when we save the patch, it may be json anyway.

namespace TPL\synths\subreal;



class Parameters {
    const OSC1_WF = 0;
    const OSC1_OCT = 1;

    const keys = array('OSC1_WF','OSC1_OCT');
}

class TestClass {

    function __construct() {
    }

    function str2enum($param) {
        return array_search('OSC1_OCT', Parameters::keys);
    }

    function pushParam($param) {
        switch($param) {
            case Parameters::OSC1_OCT:
                die('setting octave');
                break;
        }   
    }
}

$t = new TestClass();
$t->pushParam($t->str2enum('OSC1_OCT'));